### ISSUE TITLE
Grunt command is incorrect

### ISSUE THREAD

**Issue by acburdine** [sethvincent/generator-ghost#10]
After yeoman runs the ghost bower and npm installs, it attempts to run the grunt default task. However, ghost's grunt commands have changed since this was last updated, resulting in a failing generation.

Basically, instead of running `grunt default`, `grunt init` needs to be run.

**Comment by acburdine** [comment]
after doing some research into this, there are a couple of problems that are presented

* downloading the tar doesn't pull the `.git` folder, and thus even `grunt init` fails on downloading casper.
* bower install is unnecessary as grunt init takes care of that

**Comment by acburdine** [comment]
@sethvincent I'm working on a PR to fix these issues, should be finished with it in a few days.

**Comment by sethvincent** [comment]
Sounds good!

**Comment by lodybo** [comment]
Any updates for the PR?

**Comment by acburdine** [comment]
@lodybo This repo needs a pretty large refactor, which I haven't had time to do yet. I'll look at this _hopefully_ sometime this week and see what I can do.
