### ISSUE TITLE
Error with shell:ember:dev when trying to install

### ISSUE THREAD

**Issue by covertbert** [sethvincent/generator-ghost#12]
I'm getting this error when trying to run the generator:

    Running "shell:ember:dev" (shell) task
    /bin/sh: /Users/bertie.blackman/Other-Projects/GHOSTTEST/core/client/node_modules/.bin/ember: No            such file or directory
    Warning: Command failed: /bin/sh -c /Users/bertie.blackman/Other-      Projects/GHOSTTEST/core/client/node_modules/.bin/ember build
    /bin/sh: /Users/bertie.blackman/Other-Projects/GHOSTTEST/core/client/node_modules/.bin/ember: No    such file or directory
     Use --force to continue.

    Aborted due to warnings.

Any ideas?

**Comment by acburdine** [comment]
Closing as a duplicate/related to #10
