### ISSUE TITLE
no admin page

### ISSUE THREAD

**Issue by Torone** [sethvincent/generator-ghost#9]
Hi,

After installation of the version MSR1: 0.5.2 the installation and website start fine.
Going to `.../ghost` it open the first dialog to put website name, username, password.
Clicking `continue` it open correctly `.../ghost/1/` page, but the page is blank.

Best,
Andrea

**Comment by acburdine** [comment]
@Torone I'm going to close this because version 0.3 of this repository should fix this, and because that version of Ghost is a couple of years out of date.

Let me know if the problem persists after 0.3.0 and we can reopen this if necessary 😄
